//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelUploaf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Metadata
    {
        public int MetaDataId { get; set; }
        public string UserName { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<bool> Status { get; set; }
        public Nullable<int> InfoId { get; set; }
        public Nullable<int> FileId { get; set; }
        public string FileName { get; set; }
        public string Category { get; set; }
    }
}
