//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ExcelUploaf.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Miscellaneou
    {
        public int MiscellaneousId { get; set; }
        public Nullable<int> InfoId { get; set; }
        public string MiscellaneousText { get; set; }
    
        public virtual Contact Contact { get; set; }
    }
}
