//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by Microsoft.VSDesigner, Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace Soap.com.dynamics.businesscentral.api1 {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="PurchaseJournalPost_Binding", Namespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost")]
    public partial class PurchaseJournalPost : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback DeleteCurrentBatchOperationCompleted;
        
        private System.Threading.SendOrPostCallback RunCodeUnitOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public PurchaseJournalPost() {
            this.Url = global::Soap.Properties.Settings.Default.Soap_com_dynamics_businesscentral_api1_PurchaseJournalPost;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event DeleteCurrentBatchCompletedEventHandler DeleteCurrentBatchCompleted;
        
        /// <remarks/>
        public event RunCodeUnitCompletedEventHandler RunCodeUnitCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost:DeleteCurrentBatch", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost", ResponseElementName="DeleteCurrentBatch_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public void DeleteCurrentBatch(ref string batchname) {
            object[] results = this.Invoke("DeleteCurrentBatch", new object[] {
                        batchname});
            batchname = ((string)(results[0]));
        }
        
        /// <remarks/>
        public void DeleteCurrentBatchAsync(string batchname) {
            this.DeleteCurrentBatchAsync(batchname, null);
        }
        
        /// <remarks/>
        public void DeleteCurrentBatchAsync(string batchname, object userState) {
            if ((this.DeleteCurrentBatchOperationCompleted == null)) {
                this.DeleteCurrentBatchOperationCompleted = new System.Threading.SendOrPostCallback(this.OnDeleteCurrentBatchOperationCompleted);
            }
            this.InvokeAsync("DeleteCurrentBatch", new object[] {
                        batchname}, this.DeleteCurrentBatchOperationCompleted, userState);
        }
        
        private void OnDeleteCurrentBatchOperationCompleted(object arg) {
            if ((this.DeleteCurrentBatchCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.DeleteCurrentBatchCompleted(this, new DeleteCurrentBatchCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost:RunCodeUnit", RequestNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost", ResponseElementName="RunCodeUnit_Result", ResponseNamespace="urn:microsoft-dynamics-schemas/codeunit/PurchaseJournalPost", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        [return: System.Xml.Serialization.XmlElementAttribute("return_value")]
        public string RunCodeUnit(ref string batchname) {
            object[] results = this.Invoke("RunCodeUnit", new object[] {
                        batchname});
            batchname = ((string)(results[1]));
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void RunCodeUnitAsync(string batchname) {
            this.RunCodeUnitAsync(batchname, null);
        }
        
        /// <remarks/>
        public void RunCodeUnitAsync(string batchname, object userState) {
            if ((this.RunCodeUnitOperationCompleted == null)) {
                this.RunCodeUnitOperationCompleted = new System.Threading.SendOrPostCallback(this.OnRunCodeUnitOperationCompleted);
            }
            this.InvokeAsync("RunCodeUnit", new object[] {
                        batchname}, this.RunCodeUnitOperationCompleted, userState);
        }
        
        private void OnRunCodeUnitOperationCompleted(object arg) {
            if ((this.RunCodeUnitCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.RunCodeUnitCompleted(this, new RunCodeUnitCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void DeleteCurrentBatchCompletedEventHandler(object sender, DeleteCurrentBatchCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class DeleteCurrentBatchCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal DeleteCurrentBatchCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string batchname {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void RunCodeUnitCompletedEventHandler(object sender, RunCodeUnitCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class RunCodeUnitCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal RunCodeUnitCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
        
        /// <remarks/>
        public string batchname {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[1]));
            }
        }
    }
}

#pragma warning restore 1591